services:
  saudimartauth:
    build:
      context: .
      dockerfile: saudiMartAuth/Dockerfile
    container_name: saudiMartAuth
    ports:
      - "8081:8081"
    env_file: .env
    networks:
      - saudiMart_network
    volumes:
      - app_data:/var/lib/auth/data

  postgres:
    image: postgres:latest
    container_name: saudimart_postgres
    environment:
      POSTGRES_USER: saudimart
      POSTGRES_PASSWORD: saudimart
      POSTGRES_DB: saudimartdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saudiMart_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saudiMart_network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: saudimart_redisinsight
    ports:
      - "5540:5540"
    networks:
      - saudiMart_network

volumes:
  postgres_data:
  redis_data:
  app_data:

networks:
  saudiMart_network:
    driver: bridge
