services:
  postgres:
    image: postgres:latest
    container_name: saudimart_postgres
    environment:
      POSTGRES_USER: saudimart
      POSTGRES_PASSWORD: saudimart
      POSTGRES_DB: saudimartdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: saudimart_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: saudimart_redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  postgres_data:
  redis_data:

