version: "3.9"

services:
  eureka:
    build:
      context: ./Eureka
    ports:
      - "8761:8761"
    networks:
      - saudimart-network

  martauth:
    build:
      context: ./MartAuth
    ports:
      - "8081:8081"
    networks:
      - saudimart-network
    depends_on:
      - eureka
    env_file:
      - .env

  martproduct:
    build:
      context: ./MartProduct
    ports:
      - "8082:8082"
    networks:
      - saudimart-network
    depends_on:
      - eureka
    env_file:
      - .env

  martgateway:
    build:
      context: ./MartGateway
    ports:
      - "8080:8765"
    networks:
      - saudimart-network
    depends_on:
      - martauth
      - martproduct
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: saudimart_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saudimart-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saudimart-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: saudimart_redisinsight
    ports:
      - "5540:5540"
    networks:
      - saudimart-network

volumes:
  postgres_data:
  redis_data:

networks:
  saudimart-network:
    driver: bridge
