server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: MARTGATEWAY
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://MARTAUTH
          predicates:
            - Path=/users/**
            - Path=/auth/**
        - id: product-service
          uri: lb://MARTPRODUCT
          predicates:
            - Path=/api/**

jwt:
  secret: thisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKey 
  tokenValidityInMilliSeconds: 86400000 # Example: 1 day
  tokenRefreshInMilliSeconds: 604800000 # Example: 7 days