server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

spring:
  application:
    name: MARTGATEWAY

  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://SAUDIMARTAUTH
          predicates:
            - Path=/users/**,/authen/**

        - id: product-service
          uri: lb://SAUDIMARTPRODUCT
          predicates:
            - Path=/categories/**,/pricetiers/**,/productimages/**,/productspecifications/**,/productvariants/**,/products/**,/addresses/**,/contracts/**,/contractitems/**,/creditapplications/**,/inventory/**,/orderapprovals/**,/orders/**,/orderitems/**,/payments/**,/quotes/**,/quoteitems/**,/warehouses/**

jwt:
  secret: ${JWT_SECRET:salkfsdlakfsadlkfaskfldsafjlkjflksdflkwiousdfkdsflkfdfkdslfsdklafsklfdfdsf}
  tokenValidityInMilliSeconds: ${JWT_ACCESS_TOKEN_EXPIRE:86400000}
  tokenRefreshInMilliSeconds: ${JWT_REFRESH_TOKEN_EXPIRE:604800000}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
