server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring:
  application:
    name: MARTGATEWAY
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://SAUDIMARTAUTH
          predicates:
            - Path=/users/**
            - Path=/auth/**
        - id: product-service
          uri: lb://SAUDIMARTPRODUCT
          predicates:
            - Path=/api/**

jwt:
  secret: ${JWT_SECRET}
  tokenValidityInMilliSeconds: ${JWT_ACCESS_TOKEN_EXPIRE}
  tokenRefreshInMilliSeconds: ${JWT_REFRESH_TOKEN_EXPIRE}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
