server:
  port: 8081
spring:
  application:
    name: saudiMartAuth
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    username: ${REDIS_USERNAME}
jwt:
  secret: ${JWT_SECRET}
  tokenValidityInMilliSeconds: ${JWT_ACCESS_TOKEN_EXPIRE}
  tokenRefreshInMilliSeconds: ${JWT_REFRESH_TOKEN_EXPIRE}
