server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  main:
    allow-circular-references: true
  application:
    name: MARTAUTH
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/saudimartdb}
    username: ${DB_USERNAME:saudimart}
    password: ${DB_PASSWORD:saudimart}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}


jwt:
  secret: thisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKeythisissecretKey 
  tokenValidityInMilliSeconds: 86400000 # Example: 1 day
  tokenRefreshInMilliSeconds: 604800000 # Example: 7 days