server:
  port: 8082
spring:
  main:
      allow-circular-references: true
  application:
    name: MARTPRODUCT
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
jwt:
  secret: ${JWT_SECRET}
  tokenValidityInMilliSeconds: ${JWT_ACCESS_TOKEN_EXPIRE}
  tokenRefreshInMilliSeconds: ${JWT_REFRESH_TOKEN_EXPIRE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
