server:
  port: 8082
spring:
  main:
      allow-circular-references: true
  application:
    name: SAUDIMARTPRODUCT
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/saudimartdb}
    username: ${DB_USERNAME:saudimart}
    password: ${DB_PASSWORD:saudimart}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME:saudimart}
    password: ${REDIS_PASSWORD:saudimart}

jwt:
  secret: ${JWT_SECRET:salkfsdlakfsadlkfaskfldsafjlkjflksdflkwiousdfkdsflkfdfkdslfsdklafsklfdfdsf}
  tokenValidityInMilliSeconds: ${JWT_ACCESS_TOKEN_EXPIRE:86400000}
  tokenRefreshInMilliSeconds: ${JWT_REFRESH_TOKEN_EXPIRE:604800000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

