name: Build and Deploy SaudiMart Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [MartAuth, MartGateway, MartProduct, MartEureka]
        include:
          - service: MartAuth
            port: 8081
          - service: MartGateway
            port: 8080
          - service: MartProduct
            port: 8082
          - service: MartEureka
            port: 8761

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.service }}-artifact
        path: ${{ matrix.service }}/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    environment: DockerEnv
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Move artifacts to correct locations
      run: |
        for service in MartAuth MartGateway MartProduct MartEureka; do
          mkdir -p $service/target
          mv artifacts/$service-artifact/* $service/target/
        done

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        for service in MartAuth MartGateway MartProduct MartEureka; do
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${service,,}:latest $service
          docker push ${{ secrets.DOCKER_USERNAME }}/${service,,}:latest
        done
